<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Application\RentalManagementSystem.Application\RentalManagementSystem.Application.csproj" />
    <ProjectReference Include="..\..\Application\RentalManagementSystem.Domain\RentalManagementSystem.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
